### ISSUE TITLE
My local images are removed during build after installing this plugin

### ISSUE THREAD

**Issue by hafizalfaza** [bradmartin/nativescript-lottie#19]
after installing nativescript-lottie all images in ~/assets/images are not loaded
i presume it's because all images inside that folder are removed during build phase
but i don't know why

**Comment by bradmartin** [comment]
@rhanb this might bring up a good point with the dev-assets hook. We might want to be more specific with `assets/lottie` for lottie specific resources bc I sometimes put images inside an `assets` dir in my apps too 🤔 so this would bite people with lottie if that script is moving all items in `assets`. Thoughts?

**Comment by ptdede** [comment]
@bradmartin I also experienced the same issues. I heavily use shared image in my application and it's all gone after using this plugin.

**Comment by rhanb** [comment]
@bradmartin totally agree. Two solutions come to my mind:

- change the name to `android-assets` since the hook is only for android assets
- add a `nativescript-dev-assets.json` at the root of the `assets` folder and add a simple arrays of assets to delete during build face 

I prefer the second solution personnaly much more elegant 👍

**Comment by bradmartin** [comment]
I think the second approach is good so long as you can use `./*.json`, `./my-lottiefiles/*.json` instead of manually writing all the json files, I've done an app where I had 50+ and it would suck to write all 50+ out manually, even if just once ya know.

So 2nd approach if that's simple to modify the existing hook.

Also, is there a reason to 'delete' them, and not just copy? I've never really looked at the hook 🙈 so just curious.

**Comment by alexandruantonica** [comment]
I experienced the same issue. 
@rhanb I like your second idea but just to be sure I fully understood. `nativescript-dev-assets.json` inside of `assets` folder will specify what folder/files you want to be moved, isn't ?

**Comment by ptdede** [comment]
@hafizalfaza just change  ~/assets/images to ~/otherthanassets/images or just ~/images will make it back to normal for now. hahahaha.

**Comment by bradmartin** [comment]
The quickest fix would be to move to NS 4x and use the new version 2.0.0 of this plugin since now we have a true android project structure, the assets can live in app_resources.

**Comment by bradmartin** [comment]
Going to close this since 4.1.0 is released, this reduces the need for extra work on the older versions. Sorry if you aren't able to upgrade yet, in that case any PRs to fix the older version with the custom hook will be appreciated. Thanks 😄
